WITH MILK AS (SELECT CART_ID, NAME
FROM CART_PRODUCTS
WHERE NAME = 'MILK'
),

YOGURT AS (SELECT CART_ID, NAME
FROM CART_PRODUCTS
WHERE NAME = 'YOGURT'
)

SELECT DISTINCT MILK.CART_ID
FROM MILK
JOIN YOGURT ON MILK.CART_ID = YOGURT.CART_ID
WHERE MILK.CART_ID = YOGURT.CART_ID
;