SELECT INS.ANIMAL_ID AS ANIMAL_ID, INS.ANIMAL_TYPE AS ANIMAL_TYPE, INS.NAME AS NAME
FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.SEX_UPON_INTAKE != OUTS.SEX_UPON_OUTCOME
AND (SEX_UPON_OUTCOME LIKE 'Neutered%' OR SEX_UPON_OUTCOME LIKE 'Spayed%')
ORDER BY INS.ANIMAL_ID
;