
SELECT B.ID, B.NAME, B.HOST_ID
FROM(
    SELECT HOST_ID, COUNT(HOST_ID) AS HOST_ID_COUNT
    FROM PLACES
    GROUP BY HOST_ID
    HAVING HOST_ID_COUNT > 1
    ORDER BY HOST_ID
) A, PLACES B
WHERE A.HOST_ID = B.HOST_ID;
