SELECT FPRODUCT.PRODUCT_ID AS PRODUCT_ID, FPRODUCT.PRODUCT_NAME AS PRODUCT_NAME, SUM(FPRODUCT.PRICE * FORDER.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FPRODUCT
JOIN FOOD_ORDER FORDER
ON FPRODUCT.PRODUCT_ID = FORDER.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 05
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
;