SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM(
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    ORDER BY TOTAL_SALES ASC
    ) O
JOIN USED_GOODS_USER J ON O.WRITER_ID = J.USER_ID
WHERE TOTAL_SALES >= 700000
;

