SELECT DEPT.NAME AS Department, EMP.NAME AS Employee, Salary
FROM EMPLOYEE EMP
JOIN (
SELECT MAX(SALARY) AS MAXSAL, DEPARTMENTID
FROM EMPLOYEE EMP
GROUP BY DEPARTMENTID
) SALEMP ON EMP.DEPARTMENTID = SALEMP.DEPARTMENTID
JOIN DEPARTMENT DEPT ON EMP.DEPARTMENTID = DEPT.ID
WHERE SALARY = MAXSAL
;